apiVersion: v1
kind: ConfigMap
metadata:
  name: hsm-security-cams-shinobi-config
  namespace: security
data:
  conf.json: |
    {
      "db": {
        "conType": "mysql",
        "host": "127.0.0.1",
        "port": 3306,
        "user": "majesticflame",
        "password": "change-me-shinobi",
        "database": "ccio"
      },
      "videosDir": "/opt/shinobi/videos"
    }
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: hsm-security-cams-shinobi-dbinit
  namespace: security
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ccio
      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

    -- Ensure all host variants use the SAME credentials
    CREATE USER IF NOT EXISTS 'majesticflame'@'localhost' IDENTIFIED BY 'change-me-shinobi';
    CREATE USER IF NOT EXISTS 'majesticflame'@'127.0.0.1' IDENTIFIED BY 'change-me-shinobi';
    CREATE USER IF NOT EXISTS 'majesticflame'@'%' IDENTIFIED BY 'change-me-shinobi';

    ALTER USER 'majesticflame'@'localhost' IDENTIFIED BY 'change-me-shinobi';
    ALTER USER 'majesticflame'@'127.0.0.1' IDENTIFIED BY 'change-me-shinobi';
    ALTER USER 'majesticflame'@'%' IDENTIFIED BY 'change-me-shinobi';

    GRANT ALL PRIVILEGES ON ccio.* TO 'majesticflame'@'localhost';
    GRANT ALL PRIVILEGES ON ccio.* TO 'majesticflame'@'127.0.0.1';
    GRANT ALL PRIVILEGES ON ccio.* TO 'majesticflame'@'%';
    FLUSH PRIVILEGES;
