apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-shinobi-database-pvc
  namespace: security
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-shinobi-videos-pvc
  namespace: security
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi