apiVersion: v1
kind: Service
metadata:
  name: hsm-security-cams-shinobi
  namespace: security
spec:
  type: ClusterIP
  selector:
    app: hsm-security-cams-shinobi
  ports:
    - name: http
      port: 80
      targetPort: 8080