apiVersion: v1
kind: Service
metadata:
  name: hsm-be-has-gaa-gth-gsr-postulante
  namespace: app
  labels:
    app: hsm-be-has-gaa-gth-gsr-postulante
spec:
  type: ClusterIP
  selector:
    app: hsm-be-has-gaa-gth-gsr-postulante
  ports:
    - name: tcp
      port: 3000                
      targetPort: 3000
      protocol: TCP           
