apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsm-be-core-common
  namespace: app
  labels:
    app: hsm-be-core-common
  annotations:
    secrets.infisical.com/auto-redeploy: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsm-be-core-common
  template:
    metadata:
      labels:
        app: hsm-be-core-common
    spec:
      containers:
        - name: hsm-be-core-common
          image: ghcr.io/hsm-sanosoft/hsm-be-core-common:latest
          ports:
            - containerPort: 41000
          envFrom:
            - configMapRef:
                name: hsm-be-core-common-configmap
            - secretRef:
                name: hsm-be-core-common-secret
      imagePullSecrets:
        - name: ghcr-login-secret
