apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-common
  namespace: app
  labels:
    app: hsm-be-has-cob-gdp-transaccion
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/be/has/cob/gdp/transaccion"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-has-cob-gdp-transaccion-secret
      secretNamespace: app
      creationPolicy: "Owner"
      template:
        includeAllSecrets: false
        data:
          DB_USER: "{{.DB_USER.Value}}"
          DB_PASSWORD: "{{.DB_PASSWORD.Value}}"
          DB_CONNECTION_STRING: "{{.DB_CONNECTION_STRING.Value}}"
          PAGOS_API_URL: "{{.PAGOS_API_URL.Value}}"
          PAGOS_API_TOKEN_TS: "{{.PAGOS_API_TOKEN_TS.Value}}"
          PAGOS_API_TOKEN_SS: "{{.PAGOS_API_TOKEN_SS.Value}}"
          PAGOS_API_TOKEN_CS: "{{.PAGOS_API_TOKEN_CS.Value}}"
          PORCENTAJE_IVA: "{{.PORCENTAJE_IVA.Value}}"