apiVersion: v1
kind: Service
metadata:
  name: hsm-be-has-cob-gdp-transaccion
  namespace: app
  labels:
    app: hsm-be-has-cob-gdp-transaccion
spec:
  type: ClusterIP
  selector:
    app: hsm-be-has-cob-gdp-transaccion
  ports:
    - name: tcp
      port: 3000                
      targetPort: 3000
      protocol: TCP           
