apiVersion: v1
kind: Service
metadata:
  name: hsm-be-core-gateway-lb
  namespace: app
  annotations:
    metallb.universe.tf/address-pool: vip-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.251
  selector:
    app: hsm-be-core-gateway
  ports:
    - name: http
      port: 80
      targetPort: 3000
