apiVersion: v1
kind: Service
metadata:
  name: app-svc-bridge
  namespace: networking
spec:
  type: ExternalName
  externalName: hsm-be-core-gateway.app.svc.cluster.local
  ports:
    - port: 3000
      targetPort: 3000
