apiVersion: v1
kind: Service
metadata:
  name: monitoring-svc-bridge
  namespace: networking
spec:
  type: ExternalName
  externalName: grafana.monitoring.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80