apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.250
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 31572
    - name: websecure
      port: 443
      targetPort: websecure
      nodePort: 32718
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
