apiVersion: v1
kind: Service
metadata:
  name: hsm-security-cams-lb
  namespace: security
  annotations:
    metallb.universe.tf/address-pool: vip-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.1.252
  selector:
    app: hsm-security-cams
  ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
