config:
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1

  positions:
    filename: /tmp/positions.yaml

  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      pipeline_stages:
        - docker: {} 
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_name
          separator: /
          target_label: job
          replacement: $1
        - source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          separator: /
          target_label: __path__
          replacement: /var/log/pods/*$1/*.log
