apiVersion: v1
kind: Secret
metadata:
  name: loki-minio
  labels:
    app: minio
    chart: minio-5.4.0
    release: loki
    heritage: Helm
type: Opaque
data:
  rootUser: "cm9vdC11c2Vy"
  rootPassword: "c3VwZXJzZWNyZXRwYXNzd29yZA=="