apiVersion: v1
kind: Service
metadata:
  name: loki-minio-console
  labels:
    app: minio
    chart: minio-5.4.0
    release: loki
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: minio
    release: loki