loki:
  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    s3:
      endpoint: http://loki-minio.monitoring.svc.cluster.local:9000
      bucketnames: loki
      access_key_id: minioadmin
      secret_access_key: minioadmin123
      insecure: true

  pattern_ingester:
    enabled: true

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

  ruler:
    enable_api: true

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClassName: ""

deploymentMode: SingleBinary

singleBinary:
  replicas: 1

minio:
  enabled: true
  mode: standalone
  persistence:
    enabled: true
    size: 10Gi
  replicas: 1

# Disable all other components (they're not used in SingleBinary mode)
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway: 
  replicas: 0

# 🚫 No caches
chunksCache:
  enabled: false

resultsCache:
  enabled: false
