apiVersion: v1
kind: Service
metadata:
  name: hsm-be-has-gaa-gth-gsr-trabajos
  namespace: app
  labels:
    app: hsm-be-has-gaa-gth-gsr-trabajos
spec:
  type: ClusterIP
  selector:
    app: hsm-be-has-gaa-gth-gsr-trabajos
  ports:
    - name: tcp
      port: 3000                
      targetPort: 3000
      protocol: TCP           
