apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-general
  namespace: app
  labels:
    app: hsm
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/"
        recursive: true

  managedKubeSecretReferences:
    - secretName: general-secret
      secretNamespace: app
      creationPolicy: "Owner"
      template:
        includeAllSecrets: false
        data:
          JWT_SECRET: "{{.JWT_SECRET.Value}}"