apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-imagepull
  namespace: app
  labels:
    app: gateway
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "499bb8ca-329e-4281-bcf5-b316768b7865"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: dev
        secretsPath: "/"
        recursive: true

  managedKubeSecretReferences:
    - secretName: ghcr-login-secret
      secretNamespace: app
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "{{.GHCR_SERVER.Value}}": {
                  "username": "{{.GHCR_USERNAME.Value}}",
                  "password": "{{.GHCR_TOKEN.Value}}",
                  "email": "{{.GHCR_EMAIL.Value}}",
                  "auth": "{{ printf "%s:%s" .GHCR_USERNAME.Value .GHCR_TOKEN.Value | b64enc }}"
                }
              }
            }