apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-coms
  namespace: app
  labels:
    app: hsm-be-his-paciente
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/be/his/paciente"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-his-paciente-secret
      secretNamespace: app
      creationPolicy: "Owner"
      template:
        includeAllSecrets: true