apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-common
  namespace: app
  labels:
    app: hsm-be-core-common
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/be/core/common"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-core-common-secret
      secretNamespace: app
      creationPolicy: "Owner"
      template:
        includeAllSecrets: false
        data:
          DB_USER: "{{.DB_USER.Value}}"
          DB_PASSWORD: "{{.DB_PASSWORD.Value}}"
          DB_CONNECTION_STRING: "{{.DB_CONNECTION_STRING.Value}}"
          CHATWOOT_ACCOUNT_ID: "{{.CHATWOOT_ACCOUNT_ID.Value}}"
          CHATWOOT_API_KEY: "{{.CHATWOOT_API_KEY.Value}}"
          CHATWOOT_BASE_URL: "{{.CHATWOOT_BASE_URL.Value}}"
          
          