apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: hsm-networking-cloudflare-infisical-secret
  namespace: networking
  labels:
    app: hsm-networking-cloudflare
spec:
  hostAPI: https://vault.hospitalsm.org
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "a33a0079-5945-4e32-9987-14f21d2e5236"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-networking-6-ucf
        envSlug: prod
        secretsPath: ""
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-networking-cloudflare-secret
      secretNamespace: networking
      creationPolicy: "Owner"
      template:
        includeAllSecrets: false
        data:
          TUNNEL_TOKEN: "{{.CLOUDFLARE_TUNNEL_TOKEN.Value}}"
