apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsm-be-core-auth
  namespace: app
  labels:
    app: hsm-be-core-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsm-be-core-auth
  template:
    metadata:
      labels:
        app: hsm-be-core-auth
    spec:
      containers:
        - name: hsm-be-core-auth
          image: ghcr.io/hsm-sanosoft/hsm-be-core-auth:latest
          ports:
            - containerPort: 41000
          envFrom:
            - configMapRef:
                name: hsm-be-core-auth-configmap
            - secretRef:
                name: hsm-be-core-auth-secret
      imagePullSecrets:
        - name: ghcr-login-secret
