apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-auth
  namespace: app
  labels:
    app: hsm-be-core-auth
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "043936b5-a805-459f-b8f1-006941183312"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: dev
        secretsPath: "/"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-core-auth-secret
      secretNamespace: app
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          DB_USER: "{{.DB_USER.Value}}"
          DB_PASSWORD: "{{.be.core.auth.DB_PASSWORD.Value}}"
          DB_CONNECTION_STRING: "{{.be.core.auth.DB_CONNECTION_STRING.Value}}"
          JWT_SECRET: "{{.JWT_SECRET.Value}}"