apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-storage
  namespace: app
  labels:
    app: hsm-be-core-storage
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/be/core/storage"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-core-storage-secret
      secretNamespace: app
      creationPolicy: "Owner"
      template:
        includeAllSecrets: false
        data:
          MINIO_ROOT_USER: "{{.MINIO_ROOT_USER.Value}}"
          MINIO_ROOT_PASSWORD: "{{.MINIO_ROOT_PASSWORD.Value}}"
          MINIO_DOMAIN: "{{.MINIO_DOMAIN.Value}}"
          MINIO_PORT: "{{.MINIO_PORT.Value}}"
