apiVersion: v1
kind: Service
metadata:
  name: hsm-be-core-storage
  namespace: app
  labels:
    app: hsm-be-core-storage
spec:
  type: ClusterIP
  selector:
    app: hsm-be-core-storage
  ports:
    - name: server
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
