apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-coms
  namespace: app
  labels:
    app: hsm-be-core-coms
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/be/core/coms"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-core-coms-secret
      secretNamespace: app
      creationPolicy: "Owner"
      template:
        includeAllSecrets: false
        data:
          DB_USER: "{{.DB_USER.Value}}"
          DB_PASSWORD: "{{.DB_PASSWORD.Value}}"
          DB_CONNECTION_STRING: "{{.DB_CONNECTION_STRING.Value}}"
          MAIL_NAME: "{{.MAIL_NAME.Value}}"
          MAIL_API_KEY: "{{.MAIL_API_KEY.Value}}"
          MASIVA_URL: "{{.MASIVA_URL.Value}}"
          MASIVA_CLIENT_ID: "{{.MASIVA_CLIENT_ID.Value}}"
          MASIVA_CLIENT_SECRET: "{{.MASIVA_CLIENT_SECRET.Value}}"