apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: app
spec:
  secretName: app-tls-secret
  issuerRef:
    name: acme
    kind: ClusterIssuer
  dnsNames:
    - api.hospitalsm.org
    - fhir.hospitalsm.org
    - webhook.hospitalsm.org
    - openrouter.hospitalsm.org
    - openrouter-2.hospitalsm.org
