apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rsantamariao@hospitalsantamaria.com.ec
    privateKeySecretRef:
      name: acme
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik