apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-coms
  namespace: app
  labels:
    app: hsm-be-core-coms
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "499bb8ca-329e-4281-bcf5-b316768b7865"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: prod
        secretsPath: "/"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-core-coms-secret
      secretNamespace: app
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          DB_USER: "{{.DB_USER.Value}}"
          DB_PASSWORD: "{{.DB_PASSWORD.Value}}"
          DB_CONNECTION_STRING: "{{.DB_CONNECTION_STRING.Value}}"