apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-config-pvc
  namespace: security
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-recordings-pvc
  namespace: security
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-commands-pvc
  namespace: security
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
