apiVersion: v1
kind: Service
metadata:
  name: hsm-security-cams
  namespace: security
spec:
  type: ClusterIP
  selector:
    app: hsm-security-cams
  ports:
    - name: http
      port: 80
      targetPort: 8090
      protocol: TCP
