apiVersion: v1
kind: ConfigMap
metadata:
  name: hsm-be-core-gateway-configmap
  namespace: app
  labels:
    app: hsm-be-core-gateway
data:
  hsm_be_core_gateway_host: hsm-be-core-gateway.app.svc.cluster.local
  hsm_be_core_auth_host: hsm-be-core-auth.app.svc.cluster.local
  hsm_be_core_coms_host: hsm-be-core-coms.app.svc.cluster.local
  hsm_be_core_common_host: hsm-be-core-common.app.svc.cluster.local
  hsm_be_core_docs_host: hsm-be-core-docs.app.svc.cluster.local
  hsm_be_core_users_host: hsm-be-core-users.app.svc.cluster.local
  hsm_be_has_gaa_gth_gsr_postulantes_host: hsm-be-has-gaa-gth-gsr-postulantes.app.svc.cluster.local
  hsm_be_has_gaa_gth_gsr_trabajos_host: hsm-be-has-gaa-gth-gsr-trabajos.app.svc.cluster.local
  hsm_be_has_cob_gdp_transaccion_host: hsm-be-has-cob-gdp-transaccion.app.svc.cluster.local
  hsm_be_has_cob_gdp_compensacion_host: hsm-be-has-cob-gdp-compensacion.app.svc.cluster.local
  hsm_be_has_cob_gdp_recaudo_host: hsm-be-has-cob-gdp-recaudo.app.svc.cluster.local
