apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsm-be-core-gateway
  namespace: app
  labels:
    app: hsm-be-core-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsm-be-core-gateway
  template:
    metadata:
      labels:
        app: hsm-be-core-gateway
    spec:
      containers:
        - name: hsm-be-core-gateway
          image: ghcr.io/hsm-sanosoft/hsm-be-core-gateway:latest
          ports:
            - containerPort: 41000
          envFrom:
            - configMapRef:
                name: hsm-be-core-gateway-configmap
            - secretRef:
                name: hsm-be-core-gateway-secret
      imagePullSecrets:
        - name: ghcr-login-secret
