apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-gateway
  namespace: app
  labels:
    app: gateway
spec:
  hostAPI: http://10.1.1.12:80
  resyncInterval: 10
  authentication:
    kubernetesAuth:
      identityId: "2375481c-db5b-45c7-9050-e2b18ca52a61"
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-service-account
        namespace: security
      secretsScope:
        projectSlug: hsm-qq36
        envSlug: dev
        secretsPath: "/be/core/gateway"
        recursive: true

  managedKubeSecretReferences:
    - secretName: hsm-be-core-gateway-secret
      secretNamespace: app
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          DB_USER: "{{.DB_USER.Value}}"
          DB_PASSWORD: "{{.DB_PASSWORD.Value}}"
          DB_CONNECTION_STRING: "{{.DB_CONNECTION_STRING.Value}}"