apiVersion: v1
kind: Service
metadata:
  name: hsm-be-core-gateway
  namespace: app
  labels:
    app: hsm-be-core-gateway
spec:
  type: NodePort
  selector:
    app: hsm-be-core-gateway
  ports:
    - name: http
      port: 3000                
      targetPort: 41000           
