apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-frigate-config-pvc
  namespace: security
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsm-security-cams-frigate-media-pvc
  namespace: security
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn